# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ee0029d7280257b5d3aaa441f677245d576a4be1a8b8041a1c703eb374ecb9c21c9796652e045ba5fe0edb8a4af1868015c007e3c248e32dc962a025ece9a22

test:
  secret_key_base: ce9bd02470093a8f13a3d78bfbf2493ad0fc110a4f325b63946cf109743069e9f2d6946e44bec7cd904be5022bb2e6f3cfd16386ab747ca2a8a9b0f512933195

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
